module.exports.OPEN_TEST_COMMANDS_VALUE = 'OPEN_TEST_COMMANDS_VALUE';
module.exports.CLOSE_TEST_COMMANDS_VALUE = 'CLOSE_TEST_COMMANDS_VALUE';
module.exports.OPEN_ADDITIONAL_COMMANDS_VALUE =
  'OPEN_ADDITIONAL_COMMANDS_VALUE';
module.exports.CLOSE_ADDITIONAL_COMMANDS_VALUE =
  'CLOSE_ADDITIONAL_COMMANDS_VALUE';
  module.exports.OPEN_EXTRA_COMMANDS_VALUE =
  'OPEN_EXTRA_COMMANDS_VALUE';
module.exports.CLOSE_EXTRA_COMMANDS_VALUE =
  'CLOSE_EXTRA_COMMANDS_VALUE';
module.exports.COMMIT_COMMAND_VALUE = 'add . && git commit --no-edit';
